import type { HeroSlide, ServicesItem, NewsItem, SubserviceItem, ProductItem } from './types';

export const heroSlides: HeroSlide[] = [
  {
    id: 1,
    image: '/img/sections/home/home-hero-bg-1.jpg',
    imageAlt: 'Ganado en el campo',
    titleHtml:
      'La ganadería que imaginás, con el respaldo que estás <span class="text-color-4">buscando</span>.',
  },
  {
    id: 2,
    image: '/img/sections/home/home-hero-bg-1.jpg',
    imageAlt: 'Ganado en el campo',
    titleHtml:
      'La ganadería que imaginás, con el respaldo que estás <span class="text-color-4">buscando</span>.',
  },
  {
    id: 3,
    image: '/img/sections/home/home-hero-bg-1.jpg',
    imageAlt: 'Ganado en el campo',
    titleHtml:
      'La ganadería que imaginás, con el respaldo que estás <span class="text-color-4">buscando</span>.',
  },
];

export const services: ServicesItem[] = [
  {
    id: 'nutricion',
    title: 'Nutrición',
    description:
      'Nos proponemos atender y acompañar todas las etapas de la vida productiva de su animal y en las primeras etapas de vida como la Crianza o el Destete Hiperprecoz o Precoz.',
    bgClass: 'bg-color-7 nutricion-bg',
    icon: '/img/icons/icon-nutricion.svg',
    href: '/nutricion',
  },
  {
    id: 'sanidad',
    title: 'Sanidad',
    description:
      'En ACA desarrollamos un ecosistema ganadero eficiente, sostenible y rentable, integrando todos los eslabones de la cadena productiva.',
    bgClass: 'bg-color-9 sanidad-bg',
    icon: '/img/icons/icon-sanidad.svg',
    href: '/sanidad',
  },
  {
    id: 'hacienda',
    title: 'Hacienda',
    description:
      'Consolidamos un modelo productivo y comercial innovador que agrega valor a cada etapa, con foco en la trazabilidad, la calidad y el impacto positivo en el entorno.',
    bgClass: 'bg-color-11 hacienda-bg',
    icon: '/img/icons/icon-hacienda.svg',
    href: '/hacienda',
  },
  {
    id: 'produccion',
    href: '/produccion',
    title: 'Producción',
    description:
      'Compartimos soluciones y asesoramiento para potenciar cada etapa de la cadena ganadera y láctea, ayudando a productores y asesores a lograr mejores resultados.',
    bgClass: 'bg-color-13 produccion-bg',
    icon: '/img/icons/icon-produccion.svg',
  },
];

export const news: NewsItem[] = [
  {
    id: 1,
    title: 'ACA Ganadera impulsa la innovación en el sector',
    category: 'Nutrición',
    colorBadge: '',
    badgeClass: 'bg-color-7',
    date: '2025-08-19',
    image: '',
    excerpt:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e',
    href: '#',
  },
  {
    id: 2,
    title: 'ACA Ganadera impulsa la innovación en el sector',
    category: 'Sanidad',
    colorBadge: '',
    badgeClass: 'bg-color-9',
    date: '2025-08-19',
    image: '',
    excerpt:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e',
    href: '#',
  },
  {
    id: 3,
    title: 'ACA Ganadera impulsa la innovación en el sector',
    category: 'Hacienda',
    badgeClass: 'bg-color-11',
    date: '2025-08-19',
    image: '',
    excerpt:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e',
    href: '#',
  },
  {
    id: 4,
    title: 'ACA Ganadera impulsa la innovación en el sector',
    category: 'Producción',
    badgeClass: 'bg-color-13',
    date: '2025-08-19',
    image: '',
    excerpt:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do e',
    href: '#',
  },
];

export const subservicesByArea: Record<string, SubserviceItem[]> = {
  nutricion: [
    {
      icon: '/img/icons/icon-asesoramiento-en-produccion.svg',
      title: 'Asesoramiento en producción',
    },
    {
      icon: '/img/icons/icon-asesoramiento-en-formulacion-de-raciones.svg',
      title: 'Asesoramiento en formulación de raciones',
    },
    {
      icon: '/img/icons/icon-analisis-completo-de-raciones-o-materias-primas.svg',
      title: 'Análisis completo de raciones o materias primas',
    },
    {
      icon: '/img/icons/icon-venta-de-materias-primas-especificas.svg',
      title: 'Venta de materias primas específicas',
    },
  ],
};

export const heroImageMock = '/img/sections/nutricion/nutricion-hero-bg.jpg';

export const categoriesNutricion = [
  { id: '1', name: 'Porcinos' },
  { id: '2', name: 'Sistema de crianza de terneros' },
  { id: '3', name: 'Sistema de producción de leche' },
  { id: '4', name: 'Sistema de producción de carne' },
  { id: '5', name: 'Sistema de producción industrial' },
];

export const productsNutricion: ProductItem[] = [
  {
    id: 1,
    sku: '16-005570',
    name: 'Pre Starter',
    description:
      'Permiten pasar rápidamente, y minimizando el stress, de dieta líquida en lactancia a alimento sólido. La presentación especial de este alimento permite mejorar las conversiones, evitar desperdicios en comederos y optimizar la ganancia de peso.',
    generalCategory: 'nutricion',
    category: 'Porcinos',
    secondCategory:
      'Lechones a partir de los 7-10 días de vida, desde lactancia hasta los 9 kg de peso vivo.',
    presentation: 'Bolsa 25 kg',
    administration: 'Se debe controlar que la proporción utilizada sea la indicada.',
    dosage: '2 kg por lechón. A continuación de este alimento se suministrará STARTER ACA.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 2,
    sku: '16-005573',
    name: 'Starter',
    description:
      'Concentrado proteico y vitamínico mineral que permite el óptimo desarrollo de lechones en la etapa inicial y de recría. Para ser utilizado como ingrediente en la elaboración de raciones para lechones.',
    generalCategory: 'nutricion',
    category: 'Porcinos',
    secondCategory: 'Lechones hasta los 70 días de vida, posterior al concentrado iniciador.',
    presentation: 'Bolsa 25 kg',
    administration:
      'Moler adecuadamente pellets de soja y maíz de buena calidad y mezclar con AF Cerdos Concentrado Recría.',
    dosage: 'Incluir 5% de la ración.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 3,
    sku: '16-005572',
    name: 'AF Cerdos Intensivo',
    description:
      'Concentrado proteico formulado para la elaboración de raciones para lechones a partir de los 12 kg hasta los 20 kg de peso vivo.',
    generalCategory: 'nutricion',
    category: 'Porcinos',
    secondCategory: 'Lechones de 42 a 55 días de vida, entre 12 y 20 kg de peso vivo.',
    presentation: 'Bolsa 25 kg',
    administration:
      'Moler adecuadamente pellets de soja y maíz y mezclar con AF Cerdos Concentrado Iniciador.',
    dosage: 'Incluir 10% en ración con pellets de soja y maíz molido.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 4,
    sku: '16-005573',
    name: 'Cerdo Recría',
    description:
      'Concentrado proteico y vitamínico mineral que permite el óptimo desarrollo de lechones en la etapa inicial y de recría.',
    generalCategory: 'nutricion',
    category: 'Porcinos',
    secondCategory: 'Lechones hasta los 70 días de vida, continuación del concentrado iniciador.',
    presentation: 'Bolsa 25 kg',
    administration:
      'Mezclar con pellets de soja y maíz de buena calidad en proporciones adecuadas.',
    dosage: 'Incluir 5% de la ración.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 5,
    sku: '16-022002',
    name: 'Ruter VG',
    description:
      'Alimento de alta tecnología extrusado, con proteínas y grasas de máxima calidad, que mejora la eficiencia productiva y la sustentabilidad.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros de 1 a 60 días de vida en tambo o cría, según plan alimentario.',
    presentation: 'Bolsa 15 kg',
    administration: 'Consultar al departamento técnico el plan de alimentación.',
    dosage: 'Según recomendación técnica acorde al sistema de crianza.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 6,
    sku: '16-022010',
    name: 'Ruter Inicia',
    description:
      'Complemento vitamínico, mineral y energético para la crianza artificial o el destete de terneros.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros desde el primer día de vida en tambo o cría, durante 7 días.',
    presentation: '15 litros',
    administration:
      'Disolver una dosis de 50 cc en 2 litros de leche o agua a 38°C. Puede administrarse en balde, mamadera o sonda.',
    dosage: '50 cc por dosis, dos veces al día durante 7 días.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 7,
    sku: '16-023008',
    name: 'AF Mix Preparto Aniónicas',
    description:
      'Suplemento vitamínico mineral aniónico diseñado para lograr un correcto balance ácido-básico y prevenir hipocalcemia pre y post parto.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de leche',
    secondCategory: 'Vacas preparto, un mínimo de 15 días y un máximo de 21 días antes del parto.',
    presentation: 'Bolsa 25 kg',
    administration:
      'Dosificar en la ración 21 días antes del parto. Mezclar en balanceados o en mixer.',
    dosage: '300 gramos por vaca por día.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 8,
    sku: '16-023110',
    name: 'ADQ Lactancia AR',
    description:
      'Suplemento vitamínico mineral para vacas en producción desde el inicio de su lactancia.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de leche',
    secondCategory: 'Vacas lecheras en etapa de lactancia.',
    presentation: 'Bolsa 25 kg',
    administration: 'Agregar en la ración con la que se alimentan las vacas o en el mixer.',
    dosage: '300 gramos por vaca por día.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 9,
    sku: '16-023014',
    name: 'Núcleo Tambo',
    description:
      'Núcleo vitamínico y mineral formulado para la elaboración de alimentos balanceados para bovinos lecheros.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de leche',
    secondCategory: 'Vacas lecheras en producción.',
    presentation: 'Bolsa 25 kg',
    administration: 'Agregar como suplemento junto al resto de los ingredientes en la formulación.',
    dosage: '0,5 kg por tonelada.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 10,
    sku: '16-021600',
    name: 'AF Mix Industrial',
    description:
      'Suplemento vitamínico y mineral diseñado para fábricas de alimentos destinados a bovinos.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción industrial',
    secondCategory: 'Desde recría hasta animales en producción.',
    presentation: 'Bolsa 25 kg',
    administration: 'Mezclar la dosis sugerida con el resto de los ingredientes.',
    dosage: '10 kg por tonelada de alimento.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 11,
    sku: '16-007013',
    name: 'Sustituto AF',
    description:
      'Producto formulado como reemplazante de leche para alimentar a terneros durante la etapa de crianza artificial.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros en crianza artificial.',
    presentation: 'Bolsa 25 kg',
    administration: 'Calentar agua a 45/50°C y mezclar con el producto al 12%.',
    dosage: '2 tomas diarias de 2 litros cada una a 37/38°C.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 12,
    sku: '16-007001',
    name: 'Sustituto CL',
    description: 'Reemplazante de leche libre de antibióticos, con 21% de proteína y 10% de grasa.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros en crianza artificial.',
    presentation: 'Bolsa 25 kg',
    administration: 'Diluir 9 partes de agua y 1 de producto (10%).',
    dosage: '2 tomas diarias de 2 litros cada una a 37/38°C.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 13,
    sku: '16-013003',
    name: 'Rehidratante para terneros',
    description: 'Suplemento mineral con aporte de electrolitos para rehidratación de terneros.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Bovinos hasta 6 meses de edad.',
    presentation: 'Frasco 1 kg',
    administration: 'Disolver 33 g en 1 litro de agua a 38°C y administrar por mamadera o sonda.',
    dosage: '4 tomas diarias de 1 litro cada 6/8 h durante 2 días.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 14,
    sku: '16-006105',
    name: 'Arranque Terneros',
    description:
      'Alimento balanceado completo con 18% de proteína para la alimentación en crianza artificial o creep feeding.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros en crianza artificial.',
    presentation: 'Bolsa 25 kg',
    administration: 'A partir de la primera semana de vida hasta 90 kg de peso vivo.',
    dosage: 'Suministración a discreción.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 15,
    sku: '16-017111',
    name: 'Concentrado Bovinos Iniciador 40%',
    description:
      'Suplemento concentrado proteico con medicamento para preparación de raciones de bovinos y recrías.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros de 60 a 110 kg de peso vivo.',
    presentation: 'Bolsa 25 kg',
    administration: 'Combinar con granos de cereal según la categoría (10-30% de la ración).',
    dosage: 'Entre 15% y 30% de la ración según peso y etapa.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 16,
    sku: '16-017110',
    name: 'Concentrado Bovinos Terminador 40%',
    description:
      'Concentrado proteico pelleteado desarrollado para balancear dietas en vacas lecheras y engorde de bovinos.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory:
      'Animales en engorde (novillos o vaquillonas) y vacas lecheras durante la lactación.',
    presentation: 'Bolsa 25 kg',
    administration:
      'Mezclar con granos de cereal según categoría, respetando un tiempo de acostumbramiento de al menos 15 días.',
    dosage: 'Engorde: 10–20% de la ración. Lechera: 15–25% de la ración según etapa.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 17,
    sku: '16-017008',
    name: 'Concentrado Bovinos Iniciador 45%',
    description:
      'Concentrado proteico con medicamento para preparación de raciones de alimentación y engorde de bovinos o recrías en tambos.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Terneros de 60 a 110 kg de peso vivo en tambos o cría.',
    presentation: 'Bolsa 25 kg',
    administration: 'Combinar con granos de cereal (maíz, sorgo, trigo) en proporción de 10–30%.',
    dosage: 'Entre 10% y 25% de la ración, según etapa de crecimiento.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 18,
    sku: '16-017106',
    name: 'Concentrado Bovinos Terminador 45%',
    description:
      'Concentrado proteico pelleteado para balancear dietas de engorde y producción lechera.',
    generalCategory: 'nutricion',
    category: 'Sistema de crianza de terneros',
    secondCategory: 'Animales en engorde o vacas lecheras durante la lactación.',
    presentation: 'Bolsa 25 kg',
    administration:
      'Mezclar con granos de cereal según peso y categoría. Tiempo de acostumbramiento mínimo de 15 días.',
    dosage: 'Engorde: 8–15% de la ración. Lechera: 15–22% de la ración según etapa.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 19,
    sku: '16-023104',
    name: 'AF Mix ABQ Feed Lot AD',
    description:
      'Complemento vitamínico mineral para bovinos en etapa de adaptación en engorde a corral. Incluye monensina para mejorar conversión y evitar acidosis.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de carne',
    secondCategory: 'Animales desde 220 a 460 kg de peso vivo en feedlot o recría intensiva.',
    presentation: 'Bolsa 25 kg',
    administration: 'Utilizable como ingrediente de la ración o administrado ad libitum en bateas.',
    dosage:
      '2% sobre materia seca o 100–150 g diarios por animal. Usar durante los primeros 21 días de encierre.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 20,
    sku: '16-023105',
    name: 'AF Mix ABQ Feed Lot',
    description:
      'Suplemento mineral para bovinos en etapa de recría o terminación a corral. Incluye monensina para optimizar conversión y prevenir acidosis.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de carne',
    secondCategory: 'Bovinos desde 220 a 460 kg de peso vivo o en suplementación intensiva.',
    presentation: 'Bolsa 25 kg',
    administration: 'Puede ser incorporado en la ración o administrado ad libitum.',
    dosage: '2% sobre materia seca o 100–150 g diarios por animal.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 21,
    sku: '16-023103',
    name: 'AF Mix ABQ Feed Lot AR',
    description:
      'Suplemento vitamínico mineral indicado para bovinos en etapa de recría o terminación a corral. Incluye monensina para mejorar conversión y prevenir acidosis.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de carne',
    secondCategory:
      'Bovinos desde 220 a 460 kg de peso vivo, ideal para sistemas de alta performance.',
    presentation: 'Bolsa 25 kg',
    administration: 'Utilizable como ingrediente de ración o ad libitum en bateas.',
    dosage: '2% sobre materia seca o 100–150 g diarios por animal.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 22,
    sku: '16-011010',
    name: 'Microconcentrados Engorde Novillo',
    description:
      'Suplemento mineral y vitamínico con monensina para bovinos en confinamiento o suplementación a base de granos.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de carne',
    secondCategory: 'Bovinos en recría o terminación en feedlot o campo.',
    presentation: 'Bolsa 25 kg',
    administration: 'Mezclar homogéneamente con la ración. Sin período de retiro.',
    dosage: '100 g por novillo por día, mezclado en la ración.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
  {
    id: 23,
    sku: '16-011017',
    name: 'Microconcentrados Vaca Lechera',
    description: 'Suplemento vitamínico y mineral diseñado para vacas lecheras en producción.',
    generalCategory: 'nutricion',
    category: 'Sistema de producción de leche',
    secondCategory: 'Vacas lecheras en producción.',
    presentation: 'Bolsa 25 kg',
    administration: 'Suministrar junto a la ración balanceada o incorporar al mixer.',
    dosage: '100 g por vaca por día.',
    image: '/img/products/product-placeholder.png',
    price: 0,
    sales: 0,
    date: '2025-01-01',
  },
];
